name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install `stable-x86_64-unknown-linux-gnu`
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-x86_64-unknown-linux-gnu
          default: true
          profile: minimal
          components: clippy

      - name: cargo-build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --all

      - name: cargo-test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --all

      - name: cargo-clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D clippy::all -W clippy::pedantic

